In [2]:
import numpy as np

mylist_3d = [[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]],[[7,8,9],[1,2,3]]
arr_3d = np.array(mylist_3d)
print(arr_3d)

print(arr_3d.shape)

arr_3d.reshape(2,3,3)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[7 8 9]
  [1 2 3]]]
(3, 2, 3)


array([[[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 8, 9],
        [1, 2, 3]]])

In [20]:
tes = np.random.randint(0, 100, size = (2,2,3))
print(tes)


[[[11 59 67]
  [18 80 70]]

 [[ 0 30 71]
  [86 88 50]]]


In [28]:
misal = np.random.randint(0, 10, size = (6,1,3))
print(misal)

misal.reshape(3, 2, 3)

[[[7 1 7]]

 [[1 6 9]]

 [[7 3 0]]

 [[0 4 0]]

 [[9 1 8]]

 [[5 3 2]]]


array([[[7, 1, 7],
        [1, 6, 9]],

       [[7, 3, 0],
        [0, 4, 0]],

       [[9, 1, 8],
        [5, 3, 2]]])

In [31]:
misal.reshape(3, 1, 6)

array([[[7, 1, 7, 1, 6, 9]],

       [[7, 3, 0, 0, 4, 0]],

       [[9, 1, 8, 5, 3, 2]]])

In [34]:
mylist_3d = [[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]],[[7,8,9],[1,2,3]]
array_3d = np.array(mylist_3d)
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[7 8 9]
  [1 2 3]]]


In [37]:
array_3d[1]

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
array_3d[1][0]

array([4, 5, 6])

In [44]:
array_3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  4, 100, 100],
        [  7,   8,   9]],

       [[  7,   8,   9],
        [  1,   2,   3]]])

In [48]:
array_3d[1][0][2] = 100
print(array_3d)

[[[  1   2   3]
  [  4   5   6]]

 [[  4   5 100]
  [  7   8   9]]

 [[  7   8   9]
  [  1   2   3]]]


In [54]:
array_3d[1][0][0:2] = [300,200]
print(array_3d)

[[[  1   2   3]
  [  4   5   6]]

 [[300 200 100]
  [  7   8   9]]

 [[  7   8   9]
  [  1   2   3]]]


In [58]:
array_3d[0:2][0:2][0:2] = 100
print(array_3d)

[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]

 [[  7   8   9]
  [  1   2   3]]]


In [59]:
test = np.random.randint(0,50, size = (3, 2, 3))
print(test)

[[[34 47 36]
  [17 38 11]]

 [[18 27 49]
  [43 48  1]]

 [[46 27 23]
  [25 46 15]]]


In [60]:
test[0][0][1] = 1
print(test)

[[[34  1 36]
  [17 38 11]]

 [[18 27 49]
  [43 48  1]]

 [[46 27 23]
  [25 46 15]]]


In [61]:
test[2][1][2] = 1
print(test)

[[[34  1 36]
  [17 38 11]]

 [[18 27 49]
  [43 48  1]]

 [[46 27 23]
  [25 46  1]]]


In [64]:
misal = np.random.randint(0, 10, size = (3,3,3))
print(misal)

[[[6 6 7]
  [0 0 7]
  [0 6 0]]

 [[6 7 0]
  [8 1 7]
  [7 4 6]]

 [[6 9 2]
  [3 8 7]
  [3 8 1]]]


In [67]:
misal2 = np.random.randint(0, 10, size = (3,3,3))
print(misal2)

[[[5 9 7]
  [9 7 3]
  [5 9 0]]

 [[0 3 1]
  [6 8 8]
  [2 6 0]]

 [[1 8 6]
  [8 9 0]
  [0 1 9]]]


In [68]:
misal * misal2

array([[[30, 54, 49],
        [ 0,  0, 21],
        [ 0, 54,  0]],

       [[ 0, 21,  0],
        [48,  8, 56],
        [14, 24,  0]],

       [[ 6, 72, 12],
        [24, 72,  0],
        [ 0,  8,  9]]])

In [69]:
np.sqrt(misal)

array([[[2.44948974, 2.44948974, 2.64575131],
        [0.        , 0.        , 2.64575131],
        [0.        , 2.44948974, 0.        ]],

       [[2.44948974, 2.64575131, 0.        ],
        [2.82842712, 1.        , 2.64575131],
        [2.64575131, 2.        , 2.44948974]],

       [[2.44948974, 3.        , 1.41421356],
        [1.73205081, 2.82842712, 2.64575131],
        [1.73205081, 2.82842712, 1.        ]]])

In [70]:
np.power(misal, 2)

array([[[36, 36, 49],
        [ 0,  0, 49],
        [ 0, 36,  0]],

       [[36, 49,  0],
        [64,  1, 49],
        [49, 16, 36]],

       [[36, 81,  4],
        [ 9, 64, 49],
        [ 9, 64,  1]]], dtype=int32)

In [71]:
misal < 4

array([[[False, False, False],
        [ True,  True, False],
        [ True, False,  True]],

       [[False, False,  True],
        [False,  True, False],
        [False, False, False]],

       [[False, False,  True],
        [ True, False, False],
        [ True, False,  True]]])

In [72]:
misal[misal > 7]

array([8, 9, 8, 8])

In [74]:
misal1 = np.random.randint(0, 10, size = (2,4))
misal2 = np.random.randint(0, 10, size = (2,4))

In [75]:
print(misal1)

[[1 2 7 4]
 [7 9 6 6]]


In [76]:
print(misal2)

[[9 1 1 9]
 [5 9 0 1]]


In [77]:
np.concatenate((misal1,misal2), axis = 1 )

array([[1, 2, 7, 4, 9, 1, 1, 9],
       [7, 9, 6, 6, 5, 9, 0, 1]])

In [78]:
np.concatenate((misal1,misal2), axis = 0 )

array([[1, 2, 7, 4],
       [7, 9, 6, 6],
       [9, 1, 1, 9],
       [5, 9, 0, 1]])

In [79]:
misal3 = np.random.randint (0,10, size = (2,4))
print(misal3)

[[0 8 5 0]
 [5 6 3 9]]


In [80]:
misal3.T

array([[0, 5],
       [8, 6],
       [5, 3],
       [0, 9]])

In [62]:
tess = np.random.randint(0, 50, size = (3,5,3))
print(tess)

[[[35 40 13]
  [43 49 11]
  [38 16 20]
  [ 4 24  4]
  [ 5 18 34]]

 [[24 28  5]
  [ 2 10 30]
  [10 47 44]
  [35 21 31]
  [ 7 31 22]]

 [[41 32  0]
  [42 29 33]
  [20 30 16]
  [ 7  6 14]
  [46 29 41]]]


In [73]:
tess[tess > 10]

array([35, 40, 13, 43, 49, 11, 38, 16, 20, 24, 18, 34, 24, 28, 30, 47, 44,
       35, 21, 31, 31, 22, 41, 32, 42, 29, 33, 20, 30, 16, 14, 46, 29, 41])

In [82]:
tess[tess > 10] = 0
print (tess)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 4  0  4]
  [ 5  0  0]]

 [[ 0  0  5]
  [ 2 10  0]
  [10  0  0]
  [ 0  0  0]
  [ 7  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 7  6  0]
  [ 0  0  0]]]


In [3]:
tes3 = np.random.randint(0, 10, size = (3, 2))
print(tes3)

[[9 3]
 [9 0]
 [0 2]]


In [4]:
tes3b = np.random.randint(0, 10, size = (2, 3))
print(tes3b)

[[7 1 5]
 [0 5 7]]


In [5]:
np.concatenate((tes3,(tes3b.T)), axis = 1)

array([[9, 3, 7, 0],
       [9, 0, 1, 5],
       [0, 2, 5, 7]])